<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GameWave</RootNamespace>
    <AssemblyName>gamewave</AssemblyName>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.SDL" Version="2.23.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameWave.Core\GameWave.Core.csproj" />
  </ItemGroup>
</Project>
